#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from moveit_msgs.srv import GetPositionIK
from control_msgs.action import FollowJointTrajectory
from trajectory_msgs.msg import JointTrajectoryPoint
from rclpy.action import ActionClient
from builtin_interfaces.msg import Duration


class IKExecutor(Node):
    def __init__(self):
        super().__init__('ik_executor')

        # Service Client for compute_ik
        self.cli = self.create_client(GetPositionIK, '/compute_ik')
        while not self.cli.wait_for_service(timeout_sec=2.0):
            self.get_logger().info('Waiting for /compute_ik service...')

        # Action Client to send joint trajectory
        self.action_client = ActionClient(self, FollowJointTrajectory, '/arm_controller/follow_joint_trajectory')
        while not self.action_client.wait_for_server(timeout_sec=2.0):
            self.get_logger().info('Waiting for action server...')

        self.call_ik_service()

    def call_ik_service(self):
        request = GetPositionIK.Request()
        request.ik_request.group_name = 'arm'
        request.ik_request.pose_stamped.header.frame_id = 'base_link'
        request.ik_request.pose_stamped.pose.position.x = 0.1
        request.ik_request.pose_stamped.pose.position.y = 0.0
        request.ik_request.pose_stamped.pose.position.z = 0.3
        request.ik_request.pose_stamped.pose.orientation.w = 1.0  # Identity quaternion

        request.ik_request.robot_state.joint_state.name = [
            'joint_1', 'joint_2', 'joint_3', 'joint_4', 'joint_5', 'joint_6'
        ]
        request.ik_request.robot_state.joint_state.position = [0.0] * 6
        request.ik_request.avoid_collisions = True

        future = self.cli.call_async(request)
        future.add_done_callback(self.handle_ik_response)

    def handle_ik_response(self, future):
        try:
            response = future.result()
            code = response.error_code.val

            if code == 1:
                joint_names = ['joint_1', 'joint_2', 'joint_3', 'joint_4', 'joint_5', 'joint_6']
                joint_positions = response.solution.joint_state.position[:6]
                self.get_logger().info('IK solution found. Sending to action server...')
                self.send_to_action_server(joint_names, joint_positions)
            elif code == -31:
                self.get_logger().error('No IK solution found (code -31).')
            else:
                self.get_logger().error(f'IK failed with code {code}')
        except Exception as e:
            self.get_logger().error(f'Service call failed: {e}')

    def send_to_action_server(self, joint_names, joint_positions):
        from control_msgs.action import FollowJointTrajectory
        from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
        from builtin_interfaces.msg import Duration

        goal_msg = FollowJointTrajectory.Goal()
        goal_msg.trajectory.joint_names = joint_names

        point = JointTrajectoryPoint()
        point.positions = joint_positions
        point.time_from_start = Duration(sec=2)

        goal_msg.trajectory.points.append(point)

        self.get_logger().info(f'Sending trajectory: {joint_positions}')
        self.action_client.send_goal_async(goal_msg)


def main(args=None):
    rclpy.init(args=args)
    node = IKExecutor()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()

