#!/usr/bin/env bash


SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config/real_robotic_arm_controllers.yaml"

ros2 param set /real_robot/controller_manager real_arm_controller.type joint_trajectory_controller/JointTrajectoryController
ros2 run controller_manager spawner -c /real_robot/controller_manager -n real_robot -p  "$CONFIG_FILE" -t joint_trajectory_controller/JointTrajectoryController real_arm_controller

ros2 param set /real_robot/controller_manager real_state_controller.type joint_state_broadcaster/JointStateBroadcaster
ros2 run controller_manager spawner -c /real_robot/controller_manager -n real_robot -p  "$CONFIG_FILE" -t joint_state_broadcaster/JointStateBroadcaster real_state_controller

ros2 param set /real_robot/controller_manager real_gripper_controller.type joint_trajectory_controller/JointTrajectoryController
ros2 run controller_manager spawner -c /real_robot/controller_manager -n real_robot -p  "$CONFIG_FILE" -t joint_trajectory_controller/JointTrajectoryController real_gripper_controller
